package com.yueping.volunteer.model;

public enum NotificationType {
    ENROLLMENT_SUBMITTED,
    ENROLLMENT_PENDING_REVIEW,
    ENROLLMENT_APPROVED,
    ENROLLMENT_REJECTED,
    ENROLLMENT_REVIEW_PROCESSED,
    SUPPLEMENT_SUBMITTED,
    SUPPLEMENT_PENDING_REVIEW,
    SUPPLEMENT_APPROVED,
    SUPPLEMENT_REJECTED,
    SUPPLEMENT_REVIEW_PROCESSED,
    ACTIVITY_REMINDER,
    TASK_COMPLETED,
    SERVICE_CONFIRM_PENDING,
    SERVICE_RATING_RECEIVED,
    REWARD_FINALIZED,
    REWARD_FINALIZED_PROCESSED,
    REDEMPTION_CREATED,
    REDEMPTION_CREATED_OPERATOR,
    REDEMPTION_DELIVERED,
    ADMIN_APPLICATION_SUBMITTED,
    ADMIN_APPLICATION_APPROVED,
    ADMIN_APPLICATION_REJECTED,
    ADMIN_APPLICATION_REVIEW_PROCESSED
}
